name: Run ESLint Checks
on: push
jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Packages
      run: cd website && npm i
      
    - name: Run ESLint
      run: cd website && npm run lint
