name: Run ESLint Checks
on: push
jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '18.12.0'

    - name: Install Packages
      run: cd website && npm ci
      
    #- name: Run ESLint
    #  run: cd website && npm run lint

    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        eslint: true
        prettier: true
