name: Run ESLint Checks
on: push

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '18.12.0'

    - name: Install Packages
      run: cd website && npm ci
      
    #- name: Run ESLint
    #  run: cd website && npx lint-staged

    - name: Run eslint on changed files
      uses: tj-actions/eslint-changed-files@v18
      with:
        config_path: "website/.eslintrc.json"
        ignore_path: "website/.eslintignore"
        file_extensions: |
          **/*.js
          **/*.jsx
          **/*.ts
          **/*.tsx
          **/*.md
