name: team-label

on: [pull_request_target]

jobs:
  team-labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: JulienKode/team-labeler-action@v0.1.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
