name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  lint:
    name: Lint Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          version: 2.17.0

      - name: Run Vale and Reviewdog for Linting
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          vale --output=JSON . | reviewdog -f=vale -name="Vale" -reporter=github-pr-check -fail-on-error=true -filter-mode=diff_context

      - name: Run Vale for Suggestions
        run: vale --output=line . > vale_suggestions.diff

      - name: Apply Suggestions and Run Reviewdog Suggester
        uses: reviewdog/action-suggester@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: "Vale Suggestions"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            cat vale_suggestions.diff | reviewdog -f=diff -name="Vale Suggestions" -reporter=github-pr-review -filter-mode=diff_context -fail-on-error=false
