name: Reviewdog with Vale

on: [pull_request]

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Vale
      uses: errata-ai/vale-action@v2
      with:
        version: latest

    - name: Run Vale
      run: vale --output=line .
