name: Lint and Suggest

on:
  pull_request:
    paths:
      - '**/*.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Vale
      uses: errata-ai/vale-action@v2
      with:
        version: latest

    - name: Get changed files
      id: changed-files
      run: |
        BASE_SHA=$(git merge-base origin
