name: Vale Linting and Suggestions

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  vale-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Vale
        run: |
          curl -sfL https://install.goreleaser.com/github.com/errata-ai/vale.sh | sh -s -- -b $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run Vale
        run: |
          vale --output=JSON . > vale_output.json

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Process Vale Output for Reviewdog
        run: |
          jq -c '.[] | {file: .Path, line: .Line, column: .Span[0], message: .Message, suggestion: .Suggestions[0], severity: .Severity}' vale_output.json > rdjson_output.jsonl

      - name: Reviewdog - Report results and Suggest changes
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: vale
          level: warning
          reporter: github-pr-review
          filter_mode: added
          fail_on_error: true
          input_file: rdjson_output.jsonl
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
