name: Lint and Suggest

on:
  pull_request:
    paths:
      - '**/*.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history so we can access all commits

    - name: Install Vale
      uses: errata-ai/vale-action@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Get changed files
      id: changed-files
      run: |
        BASE_SHA=$(git merge-base origin/${{ github.event.pull_request.base.ref }} ${{ github.sha }})
        CHANGED_FILES=$(git diff --name-only $BASE_SHA ${{ github.sha }} -- '*.md')
        echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
        echo "CHANGED_FILES=$(echo $CHANGED_FILES | jq -R -s -c 'split(\"\n\")[:-1]')" >> $GITHUB_ENV

    - name: Print Changed Files
      run: echo $CHANGED_FILES

    - name: Run Vale on changed files
      run: |
        for file in ${{ env.CHANGED_FILES }}; do
          echo "Running Vale on $file"
          vale --output=JSON $file > "vale_output_${file//\//_}.json"
          vale --output=edit $file > "vale_output_${file//\//_}_edit.md"
        done
        echo "Vale outputs:"
        ls -l

    - name: Apply Vale edits and save originals
      run: |
        mkdir -p original_files
        mkdir -p corrected_files
        for file in ${{ env.CHANGED_FILES }}; do
          echo "Copying $file to original_files/${file//\//_}.original"
          cp "$file" "original_files/${file//\//_}.original"
          echo "Copying vale_output_${file//\//_}_edit.md to corrected_files/${file//\//_}"
          cp "vale_output_${file//\//_}_edit.md" "corrected_files/${file//\//_}"
        done
        echo "Original files:"
        ls -l original_files
        echo "Corrected files:"
        ls -l corrected_files

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Apply Vale fixes"
        git push
      continue-on-error: true

    - name: Suggest changes
      uses: parkerbxyz/suggest-changes@v1
      with:
        comment: 'Please commit the suggested changes from Vale.'
