name: Reviewdog with Vale

on: [pull_request]

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Vale
      uses: errata-ai/vale-action@v2
      with:
        version: latest

    - name: Run Vale
      run: vale --output=line .

    - name: Run Reviewdog
      uses: reviewdog/action-reviewdog@v1
      with:
        github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
        reporter: github-pr-review
        filter_mode: diff_context
        fail_on_error: false
        level: warning
        tool_name: vale
        reviewdog_flags: "-f=rdjson"
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
