name: Lint and suggest

on:
  pull_request:
    paths:
      - '**/*.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  vale: 
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history so we can access all commits
      - uses: errata-ai/vale-action@v2
    
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: '**/*.md'
          separator: ","

      - name: Print Changed Markdown Files
        run: |
          echo "Changed markdown files: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}"

      - name: Run Vale on changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
            echo "Running Vale on $file"
            vale --output=JSON $file > "vale_output_${file//\//_}.json"
            vale --output=edit $file > "vale_output_${file//\//_}_edit.md"
          done
          echo "Vale outputs:"
          ls -l

      - name: Setup reviewdog
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: vale
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}

