name: Vale Lint

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Vale and Reviewdog
      uses: errata-ai/vale-action@reviewdog
      with:
        reporter: github-pr-review
        level: warning

    - name: Run Vale on Changed Files
      run: |
        # Get the list of changed markdown files in the pull request
        CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- '*.md')
        
        # Run Vale on each changed file and report via Reviewdog
        for file in $CHANGED_FILES; do
          vale --output=JSON $file | reviewdog -f=vale -name="Vale" -reporter=github-pr-review -level=warning -filter-mode=nofilter
        done
