name: Lint and suggest

on:
  pull_request:
    paths:
      - '**/*.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        reporter: github-pr-review

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Get all changed markdown files
      id: changed-markdown-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
           **/*.md

    - name: List all changed markdown files
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
      run: |
        echo "Changed markdown files:"
        echo "${{ env.ALL_CHANGED_FILES }}"

    - name: Run Vale on changed files
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
      run: |
        for file in ${{ env.ALL_CHANGED_FILES }}; do
          echo "Running Vale on $file"
          vale --output=JSON "$file" > "vale_output_${file//\//_}.json"
        done
        echo "Vale outputs:"
        ls -l

    - name: Generate diffs from Vale outputs
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      run: |
        for file in vale_output_*.json; do
          cat "$file" | jq -r '.[] | .diff' > "diff_output_${file//\//_}.txt"
        done

    - name: Suggest changes from Vale
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        for diff in diff_output_*.txt; do
          reviewdog -f=diff -name=vale -reporter=github-pr-review -level=error < "$diff"
        done

    - name: Upload Vale outputs as artifacts
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: vale-outputs
        path: vale_output_*.json
