name: Lint and Suggest

on:
  pull_request:
    paths:
      - '**/*.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Vale
      uses: errata-ai/vale-action@v2
      with:
        version: latest

    - name: Get changed files
      id: changed-files
      run: |
        BASE_SHA=$(git merge-base origin/${{ github.event.pull_request.base.ref }} ${{ github.sha }})
        CHANGED_FILES=$(git diff --name-only $BASE_SHA ${{ github.sha }} -- '*.md')
        echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
        echo "::set-output name=files::$(echo $CHANGED_FILES | jq -R -s -c 'split(\"\\n\")[:-1]')"

    - name: Print Changed Files
      run: echo $CHANGED_FILES

    - name: Run Vale on changed files
      run: |
        for file in $(echo ${{ steps.changed-files.outputs.files }} | jq -r '.[]'); do
          echo "Running Vale on $file"
          vale --output=JSON "$file" > "vale_output_${file//\//_}.json"
        done
        echo "Vale outputs:"
        ls -l

    - name: Apply Vale suggestions
      run: |
        mkdir -p suggested_changes
        for file in $(echo ${{ steps.changed-files.outputs.files }} | jq -r '.[]'); do
          vale --output=line "$file" | grep -oP 'Consider changing.*' > suggested_changes/"$(basename "$file")".suggestions
        done

    - name: Upload Vale results
      uses: actions/upload-artifact@v3
      with:
        name: vale-results
        path: '*.json'

    - name: Upload suggested changes
      uses: actions/upload-artifact@v3
      with:
        name: suggested-changes
        path: suggested_changes/

  suggest:
    runs-on: ubuntu-latest
    needs: vale

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download suggested changes
      uses: actions/download-artifact@v3
      with:
        name: suggested-changes

    - name: List downloaded files
      run: ls -l suggested_changes

    - name: Suggest changes
      uses: parkerbxyz/suggest-changes@v1
      with:
        comment: 'Please commit the suggested changes from Vale.'
