name: Lint Markdown Files

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  vale:
    name: Vale Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vale
        uses: errata-ai/vale-action@v2
        with:
          version: 2.17.0
          files: all
          reporter: github-pr-check
          fail_on_error: true

      - name: Run Vale on changed files
        run: |
          BASE_SHA=$(git merge-base origin/${{ github.event.pull_request.base.ref }} ${{ github.sha }})
          CHANGED_FILES=$(git diff --name-only $BASE_SHA ${{ github.sha }} -- '*.md')
          for file in $CHANGED_FILES; do
            echo "Running Vale on $file"
            vale --output=JSON $file > "vale_output_${file//\//_}.json"
            vale --output=edit $file > "vale_output_${file//\//_}_edit.md"
          done

      - name: Upload Vale results
        uses: actions/upload-artifact@v3
        with:
          name: vale-results
          path: . # Uploads current directory by default

      - name: Vale Check Summary
        run: echo "Vale check completed successfully."

    env:
      GITHUB_TOKEN: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
