name: Vale Lint

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2  # Ensure sufficient depth to get the necessary commit history

    - name: Install Vale
      uses: errata-ai/vale-action@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Get changed files
      id: changed-files
      run: |
        git fetch origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}
        BASE_SHA=$(git merge-base origin/${{ github.event.pull_request.base.ref }} ${{ github.sha }})
        echo "BASE_SHA=$BASE_SHA" >> $GITHUB_ENV
        git diff --name-only $BASE_SHA ${{ github.sha }} -- '*.md' | jq -R -s -c 'split("\n") | map(select(length > 0))' > changed_files.json
        echo "::set-output name=files::$(cat changed_files.json)"

    - name: Run Vale
      run: |
        CHANGED_FILES=$(echo ${{ steps.changed-files.outputs.files }} | jq -r '.[]')
        for file in $CHANGED_FILES; do
          vale $file
        done
      shell: bash
