name: Lint Markdown with Vale and Suggest Changes

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint:
    name: Lint Markdown Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Vale
        uses: errata-ai/vale-action@v2

      - name: Lint changed markdown files
        id: vale-lint
        run: |
          changed_files=$(jq -r '.[]' <<< "${{ steps.changed-files.outputs.all_changed_and_modified_files }}")
          for file in $changed_files; do
            if [[ $file == *.md ]]; then
              vale $file || true
            fi
          done

      - name: Setup reviewdog
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: vale
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
          filter_mode: 'added'

