name: Lint and suggest

on:
  pull_request:
    paths:
      - '**/*.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        reporter: github-pr-review

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Get all changed markdown files
      id: changed-markdown-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
           **/*.md

    - name: List all changed markdown files
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
      run: |
        echo "Changed markdown files:"
        echo "${{ env.ALL_CHANGED_FILES }}"

    - name: Run Vale on changed files
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
      run: |
        for file in ${{ env.ALL_CHANGED_FILES }}; do
          echo "Running Vale on $file"
          vale --output=JSON "$file" > "vale_output_${file//\//_}.json"
        done
        echo "Vale outputs:"
        ls -l

    - name: Combine Vale JSON outputs
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      run: |
        echo "[]" > combined_vale_output.json
        for file in vale_output_*.json; do
          jq -s '.[0] + .[1]' combined_vale_output.json "$file" > tmp.json && mv tmp.json combined_vale_output.json
        done

    - name: Suggest changes from Vale
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: vale
        level: error
        reviewdog_flags: '-f=jq -name=vale -reporter=github-pr-review'
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SUGGESTION_FILE: combined_vale_output.json

    - name: Upload Vale outputs as artifacts
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: vale-outputs
        path: vale_output_*.json
